package id.fatarc.portfolio.fintechlab.review;

public enum ReviewReason {
    PROVIDER_TRANSACTION_NOT_FOUND,
    PAYMENT_INTENT_NOT_FOUND,
    AMOUNT_MISMATCH,
    CURRENCY_MISMATCH,
    STATUS_MISMATCH,
    SETTLEMENT_DATE_MISMATCH,
    DUPLICATE_PROVIDER_REFERENCE,
    INVALID_WEBHOOK_SIGNATURE,
    DUPLICATE_PROVIDER_EVENT,
    INVALID_STATE_TRANSITION,
    REFUND_BLOCKED_AFTER_RECONCILIATION
}
